"""
    Gopad OpenAPI

    API definition for Gopad  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gopad
from gopad.model.team_user_params import TeamUserParams


class TestTeamUserParams(unittest.TestCase):
    """TeamUserParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTeamUserParams(self):
        """Test TeamUserParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TeamUserParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
