# coding: utf-8

"""
    Gopad OpenAPI

    API definition for Gopad  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import gopad
from gopad.models.inline_object import InlineObject  # noqa: E501
from gopad.rest import ApiException


class TestInlineObject(unittest.TestCase):
    """InlineObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineObject(self):
        """Test InlineObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gopad.models.inline_object.InlineObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
