"""
    Gopad OpenAPI

    API definition for Gopad  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gopad
from gopad.model.team_user import TeamUser


class TestTeamUser(unittest.TestCase):
    """TeamUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTeamUser(self):
        """Test TeamUser"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TeamUser()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
