# coding: utf-8

"""
    Gopad OpenAPI

    API definition for Gopad, Etherpad for markdown with go

    The version of the OpenAPI document: 1.0.0-alpha1
    Contact: gopad@webhippie.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gopad.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_external_callback(self) -> None:
        """Test case for external_callback

        Callback for external authentication
        """
        pass

    def test_external_initialize(self) -> None:
        """Test case for external_initialize

        Initialize the external authentication
        """
        pass


if __name__ == '__main__':
    unittest.main()
