"""
    Gopad OpenAPI

    API definition for Gopad  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gopad
from gopad.model.auth_login import AuthLogin


class TestAuthLogin(unittest.TestCase):
    """AuthLogin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthLogin(self):
        """Test AuthLogin"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthLogin()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
