"""
    Gopad OpenAPI

    API definition for Gopad  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gopad
from gopad.model.auth_verify import AuthVerify


class TestAuthVerify(unittest.TestCase):
    """AuthVerify unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthVerify(self):
        """Test AuthVerify"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthVerify()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
