"""
    Gopad OpenAPI

    API definition for Gopad  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gopad
from gopad.model.user_team_params import UserTeamParams


class TestUserTeamParams(unittest.TestCase):
    """UserTeamParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserTeamParams(self):
        """Test UserTeamParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserTeamParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
