---
# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
library: urllib3
packageName: gopad
packageUrl: https://github.com/gopad/gopad-python
packageVersion: 2.6.2
projectName: gopad

...
