# flake8: noqa

"""
    Gopad OpenAPI

    API definition for Gopad  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha1
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0-alpha1"

# import ApiClient
from gopad.api_client import ApiClient

# import Configuration
from gopad.configuration import Configuration

# import exceptions
from gopad.exceptions import OpenApiException
from gopad.exceptions import ApiAttributeError
from gopad.exceptions import ApiTypeError
from gopad.exceptions import ApiValueError
from gopad.exceptions import ApiKeyError
from gopad.exceptions import ApiException
