# coding: utf-8

# flake8: noqa

"""
    Gopad OpenAPI

    API definition for Gopad, Etherpad for markdown with Go

    The version of the OpenAPI document: 1.0.0-alpha1
    Contact: gopad@webhippie.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.11.0"

# Define package exports
__all__ = [
    "AuthApi",
    "GroupApi",
    "ProfileApi",
    "UserApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AuthToken",
    "AuthVerify",
    "CreateGroupRequest",
    "CreateUserRequest",
    "DeleteGroupFromUserRequest",
    "DeleteUserFromGroupRequest",
    "Group",
    "InlineObject",
    "InlineObject1",
    "InlineObject2",
    "InlineObject3",
    "InlineObject4",
    "LoginAuthRequest",
    "Notification",
    "PermitGroupUserRequest",
    "PermitUserGroupRequest",
    "Profile",
    "Provider",
    "RedirectAuthRequest",
    "UpdateProfileRequest",
    "UpdateUserRequest",
    "User",
    "UserAuth",
    "UserGroup",
    "Validation",
]

# import apis into sdk package
from gopad.api.auth_api import AuthApi as AuthApi
from gopad.api.group_api import GroupApi as GroupApi
from gopad.api.profile_api import ProfileApi as ProfileApi
from gopad.api.user_api import UserApi as UserApi

# import ApiClient
from gopad.api_response import ApiResponse as ApiResponse
from gopad.api_client import ApiClient as ApiClient
from gopad.configuration import Configuration as Configuration
from gopad.exceptions import OpenApiException as OpenApiException
from gopad.exceptions import ApiTypeError as ApiTypeError
from gopad.exceptions import ApiValueError as ApiValueError
from gopad.exceptions import ApiKeyError as ApiKeyError
from gopad.exceptions import ApiAttributeError as ApiAttributeError
from gopad.exceptions import ApiException as ApiException

# import models into sdk package
from gopad.models.auth_token import AuthToken as AuthToken
from gopad.models.auth_verify import AuthVerify as AuthVerify
from gopad.models.create_group_request import CreateGroupRequest as CreateGroupRequest
from gopad.models.create_user_request import CreateUserRequest as CreateUserRequest
from gopad.models.delete_group_from_user_request import DeleteGroupFromUserRequest as DeleteGroupFromUserRequest
from gopad.models.delete_user_from_group_request import DeleteUserFromGroupRequest as DeleteUserFromGroupRequest
from gopad.models.group import Group as Group
from gopad.models.inline_object import InlineObject as InlineObject
from gopad.models.inline_object1 import InlineObject1 as InlineObject1
from gopad.models.inline_object2 import InlineObject2 as InlineObject2
from gopad.models.inline_object3 import InlineObject3 as InlineObject3
from gopad.models.inline_object4 import InlineObject4 as InlineObject4
from gopad.models.login_auth_request import LoginAuthRequest as LoginAuthRequest
from gopad.models.notification import Notification as Notification
from gopad.models.permit_group_user_request import PermitGroupUserRequest as PermitGroupUserRequest
from gopad.models.permit_user_group_request import PermitUserGroupRequest as PermitUserGroupRequest
from gopad.models.profile import Profile as Profile
from gopad.models.provider import Provider as Provider
from gopad.models.redirect_auth_request import RedirectAuthRequest as RedirectAuthRequest
from gopad.models.update_profile_request import UpdateProfileRequest as UpdateProfileRequest
from gopad.models.update_user_request import UpdateUserRequest as UpdateUserRequest
from gopad.models.user import User as User
from gopad.models.user_auth import UserAuth as UserAuth
from gopad.models.user_group import UserGroup as UserGroup
from gopad.models.validation import Validation as Validation
