# coding: utf-8

# flake8: noqa

"""
    Gopad OpenAPI

    API definition for Gopad  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0-alpha1"

# import apis into sdk package
from gopad.api.auth_api import AuthApi
from gopad.api.profile_api import ProfileApi
from gopad.api.team_api import TeamApi
from gopad.api.user_api import UserApi

# import ApiClient
from gopad.api_client import ApiClient
from gopad.configuration import Configuration
from gopad.exceptions import OpenApiException
from gopad.exceptions import ApiTypeError
from gopad.exceptions import ApiValueError
from gopad.exceptions import ApiKeyError
from gopad.exceptions import ApiException
# import models into sdk package
from gopad.models.auth_login import AuthLogin
from gopad.models.auth_token import AuthToken
from gopad.models.auth_verify import AuthVerify
from gopad.models.general_error import GeneralError
from gopad.models.profile import Profile
from gopad.models.team import Team
from gopad.models.team_user import TeamUser
from gopad.models.team_user_params import TeamUserParams
from gopad.models.user import User
from gopad.models.user_team_params import UserTeamParams
from gopad.models.validation_error import ValidationError
from gopad.models.validation_error_errors import ValidationErrorErrors

