# coding: utf-8

# flake8: noqa
"""
    Gopad OpenAPI

    API definition for Gopad, Etherpad for markdown with Go

    The version of the OpenAPI document: 1.0.0-alpha1
    Contact: gopad@webhippie.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from gopad.models.auth_token import AuthToken
from gopad.models.auth_verify import AuthVerify
from gopad.models.create_group_request import CreateGroupRequest
from gopad.models.create_user_request import CreateUserRequest
from gopad.models.delete_group_from_user_request import DeleteGroupFromUserRequest
from gopad.models.delete_user_from_group_request import DeleteUserFromGroupRequest
from gopad.models.group import Group
from gopad.models.inline_object import InlineObject
from gopad.models.inline_object1 import InlineObject1
from gopad.models.inline_object2 import InlineObject2
from gopad.models.inline_object3 import InlineObject3
from gopad.models.inline_object4 import InlineObject4
from gopad.models.login_auth_request import LoginAuthRequest
from gopad.models.notification import Notification
from gopad.models.permit_group_user_request import PermitGroupUserRequest
from gopad.models.permit_user_group_request import PermitUserGroupRequest
from gopad.models.profile import Profile
from gopad.models.provider import Provider
from gopad.models.redirect_auth_request import RedirectAuthRequest
from gopad.models.update_profile_request import UpdateProfileRequest
from gopad.models.update_user_request import UpdateUserRequest
from gopad.models.user import User
from gopad.models.user_auth import UserAuth
from gopad.models.user_group import UserGroup
from gopad.models.validation import Validation
