---
name: general

"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install generator
        run: npm install @openapitools/openapi-generator-cli -g

      - name: Run generate
        run: bash hack/generate-client.sh

      - name: Install requirements
        run: pip install poetry poetry-dynamic-versioning -qq

      - name: Run install
        run: poetry install

      # - name: Run format
      #   run: poetry run ruff format --check --diff ./gopad

      # - name: Run coding
      #   run: poetry run ruff check ./gopad

      - name: Run test
        run: poetry run pytest

      - name: Run build
        run: poetry build

...
